<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>wine_of_pnw</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="wine_of_pnw_files/libs/clipboard/clipboard.min.js"></script>
<script src="wine_of_pnw_files/libs/quarto-html/quarto.js"></script>
<script src="wine_of_pnw_files/libs/quarto-html/popper.min.js"></script>
<script src="wine_of_pnw_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="wine_of_pnw_files/libs/quarto-html/anchor.min.js"></script>
<link href="wine_of_pnw_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="wine_of_pnw_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="wine_of_pnw_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="wine_of_pnw_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="wine_of_pnw_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<p><strong>Abstract:</strong></p>
<p>This is a technical blog post of <strong>both</strong> an HTML file <em>and</em> <a href="src/wine_of_pnw.qmd">.qmd file</a> hosted on GitHub pages.</p>
<section id="setup" class="level1">
<h1>Setup</h1>
<ol start="2" type="1">
<li>Modify if necessary the below code so that you can successfully load <code>wine.rds</code> then delete this line.</li>
<li>In the space provided after the R chunk, explain what thecode is doing (line by line) then delete this line.</li>
<li>Get your <a href="https://docs.github.com/en/pages/quickstart">GitHub Pages</a> ready.</li>
</ol>
<p><strong>Step Up Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>wine <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">gzcon</span>(<span class="fu">url</span>(<span class="st">"https://github.com/cd-public/D505/raw/master/dat/wine.rds"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province<span class="sc">==</span><span class="st">"Oregon"</span> <span class="sc">|</span> province<span class="sc">==</span><span class="st">"California"</span> <span class="sc">|</span> province<span class="sc">==</span><span class="st">"New York"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cherry=</span><span class="fu">as.integer</span>(<span class="fu">str_detect</span>(description,<span class="st">"[Cc]herry"</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lprice=</span><span class="fu">log</span>(price)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lprice, points, cherry, province)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explanataion:</strong></p>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>:</p>
</blockquote>
<p>First, we must read in our library, which is a package of tools that do not come with R “as-is.” In other words, we need to read in the toolbox in order to use these tools (in this case, “tidyverse” is a toolbox full of tools). The RDS file is just a file full of our wine data. Filter, mutate, and select are tools from our tidyverse toolbox. Filter allows us to search data within particular parameters. In this case, we will only see wine data from Oregon, California, and New York.</p>
<p>Mutate allows us to manipulate and create existing columns. In this case, we are creating the columns “cherry” and “lprice,” which will allow us to indicate a 1 for whether or not “cherry” is in the description of the wine as well as apply a logarithm to our price in order to make it linear.</p>
</section>
<section id="multiple-regression" class="level1">
<h1>Multiple Regression</h1>
<section id="linear-models" class="level2">
<h2 class="anchored" data-anchor-id="linear-models">Linear Models</h2>
<p>First run a linear regression model with log of price as the dependent variable and ‘points’ and ‘cherry’ as features (variables).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: hint: </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> wine, lprice <span class="sc">~</span> points <span class="sc">+</span> cherry)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lprice ~ points + cherry, data = wine)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6318 -0.3377 -0.0162  0.2929  3.9586 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -5.915747   0.089938  -65.78   &lt;2e-16 ***
points       0.105104   0.001010  104.03   &lt;2e-16 ***
cherry       0.118832   0.006714   17.70   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4688 on 26581 degrees of freedom
Multiple R-squared:  0.3055,    Adjusted R-squared:  0.3054 
F-statistic:  5846 on 2 and 26581 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Explanataion:</strong></p>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>:</p>
</blockquote>
<p>In order to predict the logged price based on the number of points a wine receives as well as whether it has “cherry” in its description, we need to set up a model. First, this line of code was missing the data reference, or where the data used was coming from. Once we did this, our text editor (software) understood where it needed to pull data from. To see the results of the model, we need to use “summary(model_name).”</p>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>:</p>
</blockquote>
<p>The RMSE (Root Mean Square Error) is a measure of how accurate our model is based on averaging squared errors (errors are data that isn’t explained by our model). At 0.4688, our model is slightly better than a 50-50 chance at predicting the logged price of wine. The lower this number is, we say that the model is a “better fit.”</p>
</section>
<section id="interaction-models" class="level2">
<h2 class="anchored" data-anchor-id="interaction-models">Interaction Models</h2>
<p>Add an interaction between ‘points’ and ‘cherry’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: hint: Check the slides.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> wine, lprice <span class="sc">~</span> points <span class="sc">*</span> cherry)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lprice ~ points * cherry, data = wine)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6432 -0.3332 -0.0151  0.2924  3.9645 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -5.659620   0.102252 -55.350  &lt; 2e-16 ***
points         0.102225   0.001149  88.981  &lt; 2e-16 ***
cherry        -1.014896   0.215812  -4.703 2.58e-06 ***
points:cherry  0.012663   0.002409   5.256 1.48e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4686 on 26580 degrees of freedom
Multiple R-squared:  0.3062,    Adjusted R-squared:  0.3061 
F-statistic:  3910 on 3 and 26580 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>:</p>
</blockquote>
<p>In order to get the interaction between points and cherry, we needed to create a second model that multiplies our predictor variables together instead of adding them for a normal linear model. If we plot this and see that the lines intersect, there could be an interaction between these two variables.</p>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>:</p>
</blockquote>
<p>The RMSE of this second model with the interaction is 0.4686, which is only slightly better than our first model.</p>
<section id="the-interaction-variable" class="level3">
<h3 class="anchored" data-anchor-id="the-interaction-variable">The Interaction Variable</h3>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>: <em>interpret the coefficient on the interaction variable.</em> <br><a href="https://youtube.com/clip/UgkxY7ohjoimIef6zpPLjgQHqJcJHeZptuVm?feature=shared">Explain as you would to a non-technical manager.</a></p>
</blockquote>
<p>The coefficient (number) of the interaction variable is 0.012663, meaning that every 1 percent increase in this interaction increases our logged price by 0.012663.</p>
</section>
</section>
<section id="applications" class="level2">
<h2 class="anchored" data-anchor-id="applications">Applications</h2>
<p>Determine which province (Oregon, California, or New York), does the ‘cherry’ feature in the data affect price most?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: Create a model with an interaction between cherry and province.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>m3<span class="ot">=</span><span class="fu">lm</span>(<span class="at">data=</span>wine,lprice<span class="sc">~</span>province<span class="sc">*</span>cherry)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lprice ~ province * cherry, data = wine)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.1054 -0.3562 -0.0190  0.3623  4.1157 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              3.491711   0.004488 778.012  &lt; 2e-16 ***
provinceNew York        -0.471927   0.013697 -34.454  &lt; 2e-16 ***
provinceOregon          -0.086626   0.009792  -8.847  &lt; 2e-16 ***
cherry                   0.176729   0.009117  19.385  &lt; 2e-16 ***
provinceNew York:cherry -0.003490   0.026750  -0.130    0.896    
provinceOregon:cherry    0.126100   0.019547   6.451 1.13e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5395 on 26578 degrees of freedom
Multiple R-squared:  0.08024,   Adjusted R-squared:  0.08007 
F-statistic: 463.7 on 5 and 26578 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>: <em>write your line-by-line explanation of the code here, and explain your answer.</em></p>
</blockquote>
<p>In order to see which province the “cherry” feature affects the price most, we need to create a model with an interaction between the two columns. We can see in our model summary that Oregon is affected the most by a lot, with a coefficient larger than 0.12 and New York’s coefficient being slightly less than 0. Interestingly enough, California did not show up in the summary.</p>
<p>I checked multiple times for California in the dataset and it definitely exists in there. I believe that the software decided to leave it out for somereason. However, it is important to note that our RMSE is higher than we’ve seen when comparing the interaction between the “cherry” feature and points, indicating that this is less accurate. However, in this case, it is the trend we care more about than the actual number.</p>
</section>
</section>
<section id="scenarios" class="level1">
<h1>Scenarios</h1>
<section id="on-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="on-accuracy">On Accuracy</h2>
<p>Imagine a model to distinguish New York wines from those in California and Oregon. After a few days of work, you take some measurements and note: “I’ve achieved 91% accuracy on my model!”</p>
<p>Should you be impressed? Why or why not?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: Use simple descriptive statistics from the data to justify your answer.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>: <em>describe your reasoning here</em></p>
</blockquote>
<p>Before anyone gets impressed by this, we need to account for a few things. First, I would like to know whether our variables had any significance. I would then like to see how big our standard errors were. If our model is accurate within two standard errors in either direction, a more accurate model would be indicated with smaller standard errors. I would also argue that we should check for skewness as well for extra good measure.</p>
</section>
<section id="on-ethics" class="level2">
<h2 class="anchored" data-anchor-id="on-ethics">On Ethics</h2>
<p>Why is understanding this vignette important to use machine learning in an ethical manner?</p>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>: <em>describe your reasoning here</em></p>
</blockquote>
<p>It is important because we need to remember that just because an accuracy measure shows high accuracy or just because a variable is significant, there may be more to the story than we’re giving ourselves credit for. After all, there is such a thing as overfitting a curve, meaning it’s possible to tweak with our numbers until it says what we want it to say and that’s not ethical.</p>
</section>
<section id="ignorance-is-no-excuse" class="level2">
<h2 class="anchored" data-anchor-id="ignorance-is-no-excuse">Ignorance is no excuse</h2>
<p>Imagine you are working on a model to predict the likelihood that an individual loses their job as the result of the changing federal policy under new presidential administrations. You have a very large dataset with many hundreds of features, but you are worried that including indicators like age, income or gender might pose some ethical problems. When you discuss these concerns with your boss, she tells you to simply drop those features from the model. Does this solve the ethical issue? Why or why not?</p>
<blockquote class="blockquote">
<p><span style="color:red;font-weight:bold">TODO</span>:</p>
</blockquote>
<p>Yes and no. This would solve the ethical problem if we are looking to reduce bias on age, income, or gender. But if the dataset included other demographic data, such as race or citizenship status, then it would not eliminate all bias. That said, there is probably no way to completely remove all possibility of bias. Despite all efforts to reduce bias in this way, it is probably the case that someone will still feel disciminated against even if these indicators are removed.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>